baseurl = "https://www.diehlsillers.com/"
title = "Diehl Sillers"
author = "John Doe"
paginate = 3
theme = "arabica"

[params]
    description = "Geologist | Web Developer"
    dateFormatToUse = "2006-01-02"
    replaceGoogleFonts = "fonts.loli.net"
    twitter = "diehlsillers"
    facebook = "diehlsillers"
